name: Publish Package

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - "v[0-9]+.[0-9]+.[0-9]+"
  #     - "v[0-9]+.[0-9]+.[0-9]+-*"

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: softvisio/actions/publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tag_name: ${{ github.ref }}

      # - run: npm install
      # - run: npm run build --if-present
      # - run: npm test --if-present
      # - run: npm publish
